### PR TITLE
New config var: bool returnDronesToBayOnRetreat

### PR DESCRIPTION
**Pull request by tetreum**
Closes https://github.com/Arcitectus/Sanderling/issues/32

### CODE REVIEW

**Comment by Viir** [comment]
I am wondering about the `[NOT TESTED]`.
What would be the easiest way to test this?

I assumed that it would be sufficient to set `RetreatOnNeutralOrHostileInLocal` to true and close the chat window when in space?
What do you think about this approach?

**Comment by tetreum** [comment]
@Viir the easiest way to test it would be to let my ship be attacked by all pirates without defending my self. Which i don't kinda like it xD I currently have this changes implemented in my running bot and i'm waiting this to "naturally" happen.

About the `RetreatOnNeutralOrHostileInLocal ` option, the thing is not about retreating, is about retreating with my drones in the bay which is not happening.

**Comment by Viir** [comment]
> the easiest way to test it would be to let my ship be attacked by all pirates without defending my self. Which i don't kinda like it xD

I am not surprised that you don't like the way of testing you described.
But, I am surprised that this would be the simplest way to test the patch.

I assumed we could test the new feature with the following approach instead, which appears both simpler and less risky to me:
+ Change the configuration to set `RetreatOnNeutralOrHostileInLocal` to true.
+ Undock ship
+ Launch drones
+ Close the drones window

@tetreum, what do you think about the approach outlined above:
+ Is this a simpler way to test the new feature?
+ Do you also not like it? (If so why?)

**Comment by tetreum** [comment]
Oh, sorry i didn't understand you the first time you talked about setting `RetreatOnNeutralOrHostileInLocal ` to true . I thought you were saying that `RetreatOnNeutralOrHostileInLocal ` does already what this patch does. 
I didn't understand that you were suggesting a fast way to test it.
I will try that once i'm back home today :)

**Comment by Viir** [comment]
@tetreum , sorry I made a mistake in my description of the approach for testing. What I meant as a last step is `Close chat window` instead of `Close drones window`.

**Comment by Viir** [comment]
> Oh, sorry i didn't understand you the first time you talked about setting RetreatOnNeutralOrHostileInLocal to true.

No worries, I realized that my wording could have been better.

**Comment by tetreum** [comment]
@Viir tested, i had to make a change to make it work

**Comment by Viir** [comment]
Thanks, I am merging this then.

**Pull request merged**
