### PR TITLE
[WIP] OnClusterShutdownRetreat var

### PR DESCRIPTION
**Pull request by tetreum**
Closes https://github.com/Arcitectus/Sanderling/issues/34

### CODE REVIEW

**Comment by Viir** [comment]
What does the `[WIP]` in the title mean?

**Comment by tetreum** [comment]
Work In Progress

**Comment by Viir** [comment]
> Work In Progress

In that case, I will not look into this for now.

**Comment by tetreum** [comment]
but it is WIP because `Measurement?.AbovemainMessage` it's always null. Do you know why?

**Comment by Viir** [comment]
> `Measurement?.AbovemainMessage` it's always null. Do you know why?

I don't know why you see this.

When I have a sample of such a occurrence, I can probably fix that.

A sample can be taken with the guide from http://forum.botengine.de/t/collecting-samples-for-memory-reading-development/50

**Comment by Viir** [comment]
To clarify what should be available from `AbovemainMessage`, I dug up an example:

This screenshot shows an example of a text in `AbovemainMessage`:

**Comment by tetreum** [comment]
Sent you the measurement to your email :)

**Comment by Viir** [comment]
> Sent you the measurement to your email :)

I received an email with a process sample.

I tried to reproduce the behaviour you described, but when I loaded that sample and used the memory reader on it, it actually gave me this Text within `AbovemainMessage`: `<center>Cluster Shutdown in 3 minutes and 26 seconds`



So far I do not know how to reproduce the problem you described.

**Comment by tetreum** [comment]
:s I have this patch applied on my script and it does nothing when this message appears ingame / if i print the var is null.
Maybe i'm calling the var in a wrong way?

**Comment by Viir** [comment]
> :s I have this patch applied on my script and it does nothing when this message appears ingame / if i print the var is null.

Do you see the expected text in the [Api Explorer](https://github.com/Arcitectus/Sanderling/wiki/Bot-API#api-explorer) under `AbovemainMessage`?

**Pull request closed without merging**
