### PR TITLE
+Translate to english.

### PR DESCRIPTION
**Pull request by Viir**
+Remove code which is not needed anymore.

### CODE REVIEW

**Comment by Viir** [comment]
Goal of this change is to improve readability of the memory reading code while maintaining the resulting memory measurement.
I started this at the code which we needed to adapt most recently.

**Comment by Viir** [comment]
@dreambottle, is this what you had in mind for refactoring to english?

**Comment by dreambottle** [comment]
Yes, exactly!

**Comment by bozoweed** [comment]
can you make it compatible to other language eazy ? or maybe i gone do it if you don't

**Comment by Viir** [comment]
> can you make it compatible to other language eazy ?

How could that work? I have no idea at the moment.

**Comment by bozoweed** [comment]
we need to declare all string in all language you want able to use and make it check in the game the language if is not in list of support stop the bot and say in host.log " please use some of this language "fr en ru etc "

**Comment by bozoweed** [comment]
if you can't i gone to do that but not now , if i do it it's more latter

**Comment by bozoweed** [comment]
for now i worked on ia

**Pull request merged**
